
## Configuracion de Spring
spring:
  application:
    name: cliente-persona
  datasource:
    url: jdbc:postgresql://192.168.100.63:5433/ejercicio
    username: postgres
    password: conejoej7
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
## Configuracion de Instancia
server:
  port: 8088


